### PR TITLE
Shape Drawing: Draw predefined shapes (rectangles, circles, lines) on the canvas.

### PR DESCRIPTION
**Pull request by kavya020805**
Added Predefined Shapes(rectangle, circle, line) plus the color and size of brush or shape is dynamic so if user selects brush then the color and size will be shown for brush and if user selects circle then color and size will be shown for circle.

### CODE REVIEW

**Comment by zeeldadhaniya1895** [comment]
@kavya020805 well done

**Comment by kavya020805** [comment]
@zeeldadhaniya1895 
Can you add the hacktoberfest accepted label

**Comment by zeeldadhaniya1895** [comment]
@kavya020805 you tried to implement that for every shape color and length would be saved in local storage but it is not working can you fix that.

**Comment by zeeldadhaniya1895** [comment]
Or I will suggest don't make different state variables for every shape make a globle one and the color and size are already stored in local storage use them to set them after reload

**Comment by kavya020805** [comment]
@zeeldadhaniya1895 okay

**Pull request merged**
