### PR TITLE
Saving Functionality as required

### PR DESCRIPTION
**Pull request by atik-7866**
Do let me know if any more changes required .

### CODE REVIEW

**Comment by atik-7866** [comment]
issue #5 
@zeeldadhaniya1895 
@Aayushgoyal00

**Comment by zeeldadhaniya1895** [comment]
@atik-7866 brush color brush name needs to remain saved if you reload the page first implement this and then do PR

**Comment by atik-7866** [comment]
I hope now its fulfilling all needs fine @zeeldadhaniya1895

**Comment by zeeldadhaniya1895** [comment]
@atik-7866 Save file name also in local storage then I will merge your PR.

**Pull request merged**
